// src/components/Character.tsx
import * as React from 'react'
import { Character } from '../store/chat-state-models'
import './Character.css'

export default function CharacterView(props: { character: Character }) {
  const { name, gender, status } = props.character
  return (
    <a href="#" className="character">
      <span className={`character-status character-status-${status.toLowerCase()}`}>
        &bull;
      </span>{' '}
      <span className={`character-gender-${gender.toLowerCase()}`}>{name}</span>
    </a>
  )
}

// app/view/Character.vue
<template lang='jade'>
a(href='#')
  span(:class="'status-color ' + character.status") &bull;
  strong(:class="'gender-color ' + character.gender", :data-character='character.name')
    | {{ character.name }}
</template>

<script>
import Character from '../models/Character'

export default {
  props: {
    character: Character
  }
}
</script>
