// src/components.old/App.vue
<template>
  <main class="fullscreen bg-color-main text-color-main">
    <Loading v-if="appState === 'setup'">Setting things up...</Loading>
    <Login
      v-if="appState === 'login'"
      @submit="handleLoginSubmit"
    />
    <Loading v-if="appState === 'loggingIn'">Logging in...</Loading>
    <CharacterSelect
      v-if="appState === 'characterSelect'"
      :characters="characters"
      @submit="handleCharacterSubmit"
    />
    <Loading v-if="appState === 'connecting'">Connecting...</Loading>
    <Chat v-if="appState === 'online'" />
  </main>
</template>

<script lang="ts">
import Vue from 'vue'

import CharacterSelect from './CharacterSelect.vue'
import Chat from './chat/Chat.vue'
import Loading from './Loading.vue'
import Login from './Login.vue'

import store from '@/store'

export default Vue.extend({
  components: {
    CharacterSelect,
    Chat,
    Loading,
    Login,
  },

  data() {
    return {
      appState: '',
    }
  },

  computed: {
    characters(): string[] {
      return store.auth.characters
    },
  },

  created() {
    store.chat.disconnectFromServer()
    this.init()
  },

  methods: {
    async init() {
      this.appState = 'setup'
      try {
        await store.auth.loadAuthData()
        await store.auth.fetchCharacters()
        this.appState = 'characterSelect'
      } catch (error) {
        this.appState = 'login'
      }
    },

    async handleLoginSubmit(account: string, password: string) {
      this.appState = 'loggingIn'
      try {
        await store.auth.fetchTicket(account, password)
        await store.auth.fetchCharacters()
        store.auth.saveAuthData()
        this.appState = 'characterSelect'
      } catch (error) {
        console.log(error)
      }
    },

    handleCharacterSubmit(character: string) {
      this.appState = 'connecting'

      store.chat.connectToServer(
        store.auth.account,
        store.auth.ticket,
        character,
        this.handleConnection,
        this.handleDisconnect,
      )
    },

    handleConnection() {
      this.appState = 'online'
    },

    handleDisconnect() {
      this.init()
    },
  },
})
</script>

// src/app/components/App/App.tsx
import * as React from 'react'

import { action, observable } from 'mobx'
import { inject, observer } from 'mobx-react'

import { Loading } from 'src/app/components/Loading'
import { AppState, AppStore } from 'src/app/stores/AppStore'
import { Chat } from 'src/chat/components/Chat'

import { CharacterSelect } from './CharacterSelect'
import { Login } from './Login'

type AppProps = {
  store?: AppStore
}

@inject('store')
@observer
export class App extends React.Component<AppProps> {
  @observable loginStatus = ''

  @action.bound
  async init() {
    const store = this.props.store!
    try {
      await store.auth.loadAuthData()
      await store.auth.fetchCharacters()
      store.setState(AppState.characterSelect)
    } catch {
      store.setState(AppState.login)
    }
  }

  @action.bound
  async handleLoginSubmit(username: string, password: string) {
    const store = this.props.store!

    try {
      this.loginStatus = 'Logging in...'

      await store.auth.fetchTicket(username, password)
      await store.auth.fetchCharacters()

      store.auth.saveAuthData().catch(console.error)
      store.setState(AppState.characterSelect)

      this.loginStatus = ''
    } catch (error) {
      this.loginStatus = error.message || error.toString()
    }
  }

  @action.bound
  handleCharacterSubmit(character: string) {
    const store = this.props.store!
    const { account, ticket } = store.auth

    store.setState(AppState.connecting)

    store.chat.connectToServer(
      account,
      ticket,
      character,
      this.handleConnect,
      this.handleDisconnect,
    )
  }

  @action.bound
  handleConnect() {
    this.props.store!.setState(AppState.online)
  }

  @action.bound
  handleDisconnect() {
    this.init()
  }

  async componentDidMount() {
    await this.init()
  }

  renderCurrentView() {
    const store = this.props.store!

    switch (store.state) {
      case AppState.setup:
        return <Loading text="Setting things up..." />

      case AppState.login:
        return <Login statusText={this.loginStatus} onSubmit={this.handleLoginSubmit} />

      case AppState.characterSelect:
        return (
          <CharacterSelect
            characters={store.auth.characters}
            onSubmit={this.handleCharacterSubmit}
          />
        )

      case AppState.connecting:
        return <Loading text="Connecting..." />

      case AppState.online:
        return <div>am chat</div>
    }
  }

  render() {
    return (
      <main className="fullscreen flex-center bg-color-main text-color-main">
        {/* this.renderCurrentView() */}
        <Chat />
      </main>
    )
  }
}
