// src/components/CharacterSelect.vue
<template>
  <overlay>
    <div style="text-align: center; padding: 0rem 1rem 1rem">
      <h1>Choose your identity.</h1>
      <p>
        <img :src="avatarURL" :alt="'Avatar for ' + selected" />
      </p>
      <form @submit.prevent="submit">
        <fieldset>
          <select v-model="selected">
            <option v-for="name in characters" :key="name">{{ name }}</option>
          </select>
        </fieldset>
        <fieldset>
          <button type="submit">Submit</button>
        </fieldset>
      </form>
    </div>
  </overlay>
</template>

<script lang="ts">
import Vue from 'vue'
import forage from 'localforage'
import { getAvatarURL } from '@/api'

const storageKey = 'CharacterSelect_lastCharacter'

export default Vue.extend({
  props: {
    characters: Array
  },

  data() {
    return {
      selected: ''
    }
  },

  computed: {
    avatarURL(): string {
      return getAvatarURL(this.selected)
    },
  },

  async created() {
    this.selected =
      (await forage.getItem<string>(storageKey)) || this.characters[0] || ''
  },

  methods: {
    submit() {
      this.$emit('submit', this.selected)
    },
  },

  watch: {
    selected(value) {
      forage.setItem(storageKey, value)
    },
  },
})
</script>

// src/app/components/App/CharacterSelect.tsx
import { bind } from 'decko'
import { action, observable } from 'mobx'
import { observer } from 'mobx-react'
import * as React from 'react'
import { getAvatarURL } from 'src/api'
import { preventDefault } from 'src/common/util/react'
import { StoredValue } from 'src/common/util/stored-value'

type CharacterSelectProps = {
  characters: string[]
  onSubmit: (character: string) => void
}

@observer
export class CharacterSelect extends React.Component<CharacterSelectProps> {
  @observable character = ''
  storedCharacter = new StoredValue<string>('CharacterSelect_character')

  @bind
  handleSubmit() {
    this.props.onSubmit(this.character)
  }

  @action.bound
  handleChange(event: React.ChangeEvent<HTMLSelectElement>) {
    this.character = event.currentTarget.value
    this.storedCharacter.save(this.character).catch(console.error)
  }

  async componentDidMount() {
    const initialCharacter = await this.storedCharacter.restore()
    this.character = initialCharacter || ''
  }

  render() {
    return (
      <section className="text-center">
        <h1>Choose your identity.</h1>
        <p>
          <img src={getAvatarURL(this.character)} alt={`Avatar for ${this.character}`} />
        </p>
        <form onSubmit={preventDefault(this.handleSubmit)}>
          <fieldset>
            <select value={this.character} onChange={this.handleChange}>
              {this.props.characters.map(name => <option key={name}>{name}</option>)}
            </select>
          </fieldset>
          <fieldset>
            <button type="submit">Submit</button>
          </fieldset>
        </form>
      </section>
    )
  }
}
