// src/chat/components/Message.vue
<template>
  <div :class="['message', isAction && 'message-action']">
    <div style="padding: 0.4rem 0.6rem" :class="'message-type-' + type">
      <span class="message-time">{{ parsedDate }}</span>
      <character-name v-bind="getCharacter(sender)"></character-name>
      <span class="message-text" v-html="parseBBC(parsedText)"></span>
    </div>
  </div>
</template>

<script>
import { parseBBC } from '@/chat/bbc'
import { getAvatarURL, getProfileURL } from '@/chat/helpers'

export default {
  props: {
    sender: String,
    text: String,
    type: String,
    date: Date,
  },
  components: {
    CharacterName: require('./CharacterName.vue').default,
  },
  methods: {
    getAvatarURL,
    getProfileURL,
    parseBBC,
  },
  computed: {
    characters() {
      return this.$store.state.chat.characters
    },
    getCharacter() {
      return this.$store.getters.getCharacter
    },
    isAction() {
      return this.text.startsWith('/me')
    },
    parsedText() {
      if (this.isAction) {
        return this.text.replace(/^\/me\s*/, '')
      }
      return this.text
    },
    parsedDate() {
      return this.date.toLocaleTimeString()
    }
  },
}
</script>

<style lang="scss" scoped>
.message-type-lfrp {
  background-color: rgba(46, 204, 113, 0.1);
}

.message:nth-child(2n) {
  background-color: rgba(black, 0.1);
}

.message-action {
  font-style: italic;
}

.message-text {
  white-space: pre-wrap;
  word-break: break-word;
  margin-left: 0.3rem;
}

.message-time {
  opacity: 0.3;
  float: right;
  font-size: 75%;
}
</style>

// src/message/components/MessageComponent.tsx
import * as React from 'react'
import { CharacterName } from 'src/character/components/CharacterName'
import { parseBBC } from 'src/chat/util/bbc'
import { Message, MessageType } from 'src/message/models/Message'
import styled from 'styled-components'

const actionExp = /^\s*\/me\s*/

const Wrapper = styled.div`
  &:nth-child(2n) {
    background-color: rgba(0, 0, 0, 0.15);
  }
`

function getHighlightClass(messageType: MessageType) {
  switch (messageType) {
    case 'normal':
      return ''
    case 'lfrp':
      return 'highlight-green'
    case 'admin':
      return 'highlight-red'
    case 'system':
      return ''
  }
}

export function MessageComponent(props: { message: Message }) {
  const { sender, text, type, date } = props.message
  const isAction = text.trim().startsWith('/me')
  const parsedText = parseBBC(text.replace(actionExp, ''))

  const actionClass = isAction ? 'text-italic' : ''
  const highlightClass = getHighlightClass(type)

  return (
    <Wrapper className={`${actionClass}`}>
      <div className={`padding ${highlightClass}`}>
        <span className="margin-left text-small text-italic faded float-right">
          [{date.toLocaleTimeString()}]
        </span>
        <span className="margin-right">
          <CharacterName name={sender} />
        </span>
        <span className={`preserve-ws`} dangerouslySetInnerHTML={{ __html: parsedText }} />
      </div>
    </Wrapper>
  )
}
