// src/components/Login.tsx
import * as React from 'react'
import Toggle from './Toggle'

export type LoginSubmitCallback = (username: string, password: string) => any

export default class Login extends React.Component {
  props: { status: string; onSubmit: LoginSubmitCallback }

  state = { username: '', password: '' }

  updateUsername = (event: React.SyntheticEvent<HTMLInputElement>) => {
    this.setState({
      username: event.currentTarget.value,
    })
  }

  updatePassword = (event: React.SyntheticEvent<HTMLInputElement>) => {
    this.setState({
      password: event.currentTarget.value,
    })
  }

  handleSubmit = (event: React.SyntheticEvent<HTMLFormElement>) => {
    const { username, password } = this.state
    this.props.onSubmit(username, password)
  }

  render() {
    return (
      <div>
        <h2>Hello, beautiful.</h2>
        <form onSubmit={this.handleSubmit}>
          <fieldset className="form-icon-input">
            <i className="mdi mdi-account-circle" />
            <input
              type="text"
              placeholder="Username"
              value={this.state.username}
              onInput={this.updateUsername}
            />
          </fieldset>
          <fieldset className="form-icon-input">
            <i className="mdi mdi-lock" />
            <input
              type="password"
              placeholder="••••••••"
              value={this.state.password}
              onInput={this.updatePassword}
            />
          </fieldset>
          <fieldset>
            <Toggle value={false}>Remember</Toggle>
          </fieldset>
          <fieldset>
            <button className="form-button" formAction="submit">
              Go
            </button>
          </fieldset>
        </form>
        <p className="status" style={{ maxWidth: '16em' }}>
          {this.props.status}
        </p>
      </div>
    )
  }
}

// src.old/components/Login.vue
<template>
  <form @submit.prevent='submit'>
    <fieldset>
      <h2>Hello, beautiful.</h2>
    </fieldset>
    <fieldset>
      <div class='form-icon-input'>
        <i class='mdi mdi-account-circle'></i>
        <input type='text' placeholder='Username' v-model='account'/>
      </div>
    </fieldset>
    <fieldset>
      <div class='form-icon-input'>
        <i class='mdi mdi-lock'></i>
        <input type='password' placeholder='••••••••' v-model='password'/>
      </div>
    </fieldset>
    <fieldset>
      <toggle v-model='remember'>Remember me</toggle>
    </fieldset>
    <fieldset>
      <button class='form-button' action='submit'>Go</button>
    </fieldset>
    <fieldset>
      <div class='status'>
        {{ status }}
      </div>
    </fieldset>
  </form>
</template>

<script>
import Toggle from './Toggle.vue'
import * as flist from '../lib/f-list'
import * as storage from 'localforage'
import {store} from '../store'

export default {
  components: {
    Toggle,
  },
  data() {
    return {
      account: '',
      password: '',
      remember: false,
      status: '',
    }
  },
  async created() {
    const auth = await storage.getItem('auth')
    if (auth) {
      this.account = auth.account
      this.remember = true
    }
  },
  methods: {
    submit() {
      this.status = ''
      store.login(this.account, this.password, this.remember).catch(err => {
        this.status = err
      })
    },
  },
}
</script>

<style lang='stylus' scoped>
@require 'vars'

form
  text-align: center

.status
  max-width: 16em
</style>
