// src/components/CharacterSelect.tsx
import * as React from 'react'
import { getAvatarURL } from '../lib/f-list'
import { InputEvent, preventDefault } from '../lib/react-utils'

const avatarStyle: React.CSSProperties = {
  width: '100px',
  height: '100px',
}

export default class CharacterSelect extends React.Component {
  props: {
    characters: string[]
    onSubmit: (character: string) => any
  }

  state = {
    current: '',
  }

  handleSubmit = () => {
    this.props.onSubmit(this.state.current)
  }

  handleChange = (event: InputEvent) => {
    const { value } = event.currentTarget
    this.setState({ current: value })
    localStorage.setItem('lastCharacter', value)
  }

  componentDidMount() {
    this.setState({ current: localStorage.getItem('lastCharacter') || this.props.characters[0] })
  }

  render(): JSX.Element {
    const { current } = this.state
    return (
      <form onSubmit={preventDefault(this.handleSubmit)}>
        <fieldset>
          <img src={getAvatarURL(current)} alt={`Avatar for ` + current} style={avatarStyle} />
        </fieldset>
        <fieldset>
          <select className='input' value={current} onChange={this.handleChange}>
            {this.props.characters.map(name =>
              <option key={name}>
                {name}
              </option>
            )}
          </select>
        </fieldset>
        <fieldset>
          <button className='button' action='submit'>
            Confirm
          </button>
        </fieldset>
      </form>
    )
  }
}

// src/app/components/CharacterSelect.vue
<template>
  <overlay>
    <div style="text-align: center; padding: 0rem 1rem 1rem">
      <h1>Choose your identity.</h1>
      <p>
        <img :src="avatarURL" :alt="'Avatar for ' + selected" />
      </p>
      <form @submit.prevent="submit">
        <fieldset>
          <select v-model="selected">
            <option v-for="name in characters" :key="name">{{ name }}</option>
          </select>
        </fieldset>
        <fieldset>
          <button type="submit">Submit</button>
        </fieldset>
      </form>
    </div>
  </overlay>
</template>

<script>
import forage from 'localforage'
import { getAvatarURL } from '@/chat/helpers'

export default {
  computed: {
    characters() {
      return this.$store.state.user.characters
    },
    avatarURL() {
      return getAvatarURL(this.selected)
    },
  },
  data() {
    return {
      selected: '',
    }
  },
  async created() {
    this.selected =
      (await forage.getItem('lastCharacter')) || this.characters[0] || ''
  },
  methods: {
    submit() {
      this.$emit('submit', this.selected)
    },
  },
  watch: {
    selected(value) {
      forage.setItem('lastCharacter', value)
    },
  },
}
</script>
