// src/view/components/overlays/Loading.vue
<template>
  <div class="ui-shade flex-column flex-center-children" transition="fade">
    <i class="fa fa-paw"></i>
    <h3><em>Working on it...</em></h3>
  </div>
</template>

<style lang="stylus" scoped>
turning($x, $y, $z)
  transform: perspective(300px) rotateX(unit($x, turn)) rotateY(unit($y, turn)) rotateZ(unit($z, turn))

@keyframes rotate
  0% { turning: 0 0 0 }
  25% { turning: 0 0.5 0 }
  50% { turning: 0.5 0.5 0 }
  75% { turning: 0.5 1 0 }
  100% { turning: 1 1 0 }

i
  font-size: 5em
  animation-name: rotate
  animation-duration: 3.5s
  animation-iteration-count: infinite
  animation-timing-function: ease-out

i, h3
  color: rgba(white, 0.7)
</style>

<script></script>

// src/app/components/Loading.tsx
import * as React from 'react'
import styled, { keyframes } from 'styled-components'
import { Icon } from 'src/app/components/Icon'

const Shade = styled.div`
  background: rgba(0, 0, 0, 0.5);
`

const iconAnimation = keyframes`
  0% { transform: perspective(180px) rotateX(0) rotateY(0); }
  25% { transform: perspective(180px) rotateX(0.5turn) rotateY(0); }
  50% { transform: perspective(180px) rotateX(0.5turn) rotateY(0.5turn); }
  75% { transform: perspective(180px) rotateX(1turn) rotateY(0.5turn); }
  100% { transform: perspective(180px) rotateX(1turn) rotateY(1turn); }
`

const AnimatedIcon = styled(Icon)`
  animation: ${iconAnimation} 4s infinite;
  opacity: 0.3;
`

type LoadingProps = { text: string }

export function Loading(props: LoadingProps) {
  return (
    <Shade className="fullscreen flex-column flex-center">
      <div>
        <AnimatedIcon name="paw" size={100} />
      </div>
      <h2 className="text-italic">{props.text}</h2>
    </Shade>
  )
}
