// src/app/components/Loading.vue
<template>
  <div class='shade'>
    <div class='icon'>
      <i class='mdi mdi-paw'></i>
    </div>
    <h3 class='text'>
      <slot></slot>
    </h3>
  </div>
</template>

<script>
export default {}
</script>

<style lang='stylus' scoped>
@require 'theme'
@require 'layout'
@require 'flex'

.shade
  fullscreen()
  flex(column)
  flex-align(center)
  background: rgba(black, 0.5)

.icon
  font-size: 500%
  animation: loading-animation 3s infinite

.text
  font-style: italic

@keyframes loading-animation
  0%   { transform: perspective(120px) rotateX(0) rotateY(0) }
  25%  { transform: perspective(120px) rotateX(0.5turn) rotateY(0) }
  50%  { transform: perspective(120px) rotateX(0.5turn) rotateY(0.5turn) }
  75%  { transform: perspective(120px) rotateX(1turn) rotateY(0.5turn) }
  100% { transform: perspective(120px) rotateX(1turn) rotateY(1turn) }
</style>

// src/app/components/Loading.tsx
import * as React from 'react'
import styled, { keyframes } from 'styled-components'
import { Icon } from 'src/app/components/Icon'

const Shade = styled.div`
  background: rgba(0, 0, 0, 0.5);
`

const iconAnimation = keyframes`
  0% { transform: perspective(180px) rotateX(0) rotateY(0); }
  25% { transform: perspective(180px) rotateX(0.5turn) rotateY(0); }
  50% { transform: perspective(180px) rotateX(0.5turn) rotateY(0.5turn); }
  75% { transform: perspective(180px) rotateX(1turn) rotateY(0.5turn); }
  100% { transform: perspective(180px) rotateX(1turn) rotateY(1turn); }
`

const AnimatedIcon = styled(Icon)`
  animation: ${iconAnimation} 4s infinite;
  opacity: 0.3;
`

type LoadingProps = { text: string }

export function Loading(props: LoadingProps) {
  return (
    <Shade className="fullscreen flex-column flex-center">
      <div>
        <AnimatedIcon name="paw" size={100} />
      </div>
      <h2 className="text-italic">{props.text}</h2>
    </Shade>
  )
}
