// src/components/Login.tsx
import * as React from 'react'
import Toggle from './Toggle'

export type LoginSubmitCallback = (username: string, password: string) => any

export default class Login extends React.Component {
  props: { status: string; onSubmit: LoginSubmitCallback }

  state = { username: '', password: '' }

  updateUsername = (event: React.SyntheticEvent<HTMLInputElement>) => {
    this.setState({
      username: event.currentTarget.value,
    })
  }

  updatePassword = (event: React.SyntheticEvent<HTMLInputElement>) => {
    this.setState({
      password: event.currentTarget.value,
    })
  }

  handleSubmit = (event: React.SyntheticEvent<HTMLFormElement>) => {
    const { username, password } = this.state
    this.props.onSubmit(username, password)
  }

  render() {
    return (
      <div>
        <h2>Hello, beautiful.</h2>
        <form onSubmit={this.handleSubmit}>
          <fieldset className="form-icon-input">
            <i className="mdi mdi-account-circle" />
            <input
              type="text"
              placeholder="Username"
              value={this.state.username}
              onInput={this.updateUsername}
            />
          </fieldset>
          <fieldset className="form-icon-input">
            <i className="mdi mdi-lock" />
            <input
              type="password"
              placeholder="••••••••"
              value={this.state.password}
              onInput={this.updatePassword}
            />
          </fieldset>
          <fieldset>
            <Toggle value={false}>Remember</Toggle>
          </fieldset>
          <fieldset>
            <button className="form-button" formAction="submit">
              Go
            </button>
          </fieldset>
        </form>
        <p className="status" style={{ maxWidth: '16em' }}>
          {this.props.status}
        </p>
      </div>
    )
  }
}

// src/app/components/Login.vue
<template lang='pug'>
form.login-form(@submit.prevent='submit')
  fieldset
    h2 Hello, beautiful.
  fieldset
    .icon-input
      i.mdi.mdi-account-circle
      input(type='text', placeholder='Username', v-model='account')
  fieldset
    .icon-input
      i.mdi.mdi-lock
      input(type='password', placeholder='••••••••', v-model='password')
  fieldset
    button.button Go
  fieldset
    toggle(v-model="remember") Remember me
</template>

<script>
import Toggle from './Toggle.vue'

export default {
  components: {
    Toggle
  },
  data () {
    return {
      account: '',
      password: '',
      remember: false
    }
  },
  methods: {
    submit () {
      // log in
    }
  }
}
</script>
