// src/components/Toggle.tsx
import * as React from 'react'
import css from './Toggle.styl?module'

export default class Toggle extends React.Component {
  props: {
    value: boolean
    children: React.ReactNode
  }

  render() {
    const iconClass = this.props.value
      ? 'mdi-checkbox-marked-outline'
      : 'mdi-checkbox-blank-outline'

    return (
      <a className={css.toggle} href="#">
        <i className={`mdi ${iconClass}`} /> {this.props.children}
      </a>
    )
  }
}

// src/app/components/Toggle.vue
<template lang='pug'>
a.toggle(href='#', :class!="value && 'toggle-checked'", @click.prevent="$emit('input', !value)")
  i.mdi(:class="iconClass")
  span.icon-label
    slot
</template>

<script>
export default {
  props: {
    value: Boolean
  },
  computed: {
    iconClass () {
      return this.value
        ? 'mdi-checkbox-marked-outline'
        : 'mdi-checkbox-blank-outline'
    }
  }
}
</script>
