// src/components/Chat/CharacterName.vue
<template>
  <a href='#' class='character' :name='name' :href="profileURL" target="_blank" :data-character="name">
    <span v-if='status' :class='statusClass' :title="status">•</span>
    <span :class='genderClass'>{{ name }}</span>
  </a>
</template>

<script>
import { getProfileURL } from '@/api'

export default {
  props: {
    name: { type: String, required: true },
    gender: { type: String, default: 'none' },
    status: String,
  },
  computed: {
    statusClass() {
      return 'character-status-' + this.status.toLowerCase()
    },
    genderClass() {
      return 'character-gender-' + this.gender.toLowerCase()
    },
    profileURL() {
      return getProfileURL(this.name)
    },
  },
}
</script>

<style lang='scss' scoped>
.character {
  font-weight: bold;
}

.ignored {
  opacity: 0.5;
}
</style>

// src/character/components/CharacterName.tsx
import { inject, observer } from "mobx-react"
import * as React from "react"
import styled from "react-emotion"
import { getProfileURL } from "src/api"
import { CharacterStore } from "src/character/stores/CharacterStore"

type Props = {
  name: string
  characterStore?: CharacterStore
}

const StatusDot = styled("span")`
  line-height: 0;
  font-size: 120%;
  vertical-align: middle;
`

function renderCharacterName(props: Props) {
  const { name } = props
  const { gender, status } = props.characterStore!.getCharacter(name)
  const genderClass = "character-gender-" + gender.toLowerCase()
  const statusClass = "character-status-" + status.toLowerCase()

  return (
    <a
      href={getProfileURL(name)}
      target="_blank"
      className={`${genderClass} text-bold`}
      data-character={name}
    >
      <StatusDot className={statusClass} title={status}>
        &bull;
      </StatusDot>{" "}
      {name}
    </a>
  )
}

export const CharacterName = inject("characterStore")(observer(renderCharacterName))
