// src/components/chat/ChannelView.vue
<template>
  <main class="flex-column">
    <section class="scroll-v" style="height: 5rem; padding: 0.3rem 0.6rem">
      <span v-html="parseBBC(description)"></span>
    </section>
    <div class="flex-grow flex-row">
      <section class="flex-grow bg-color-darken-1 scroll-v">
        <message v-for="(message, i) in messages" v-bind="message" :key="i"></message>
      </section>
      <section class="scroll-v" style="width: 12rem">
        <user-list :users="users"></user-list>
      </section>
    </div>
    <section class="bg-color-main flex-row" style="height: 5rem; padding: 0.3rem;">
      <chatbox class="flex-grow" @submit="sendMessage"></chatbox>
    </section>
  </main>
</template>

<script>
import { parseBBC } from '../../bbc'

export default {
  components: {
    CharacterName: require('./CharacterName.vue'),
    UserList: require('./UserList.vue'),
    Message: require('./Message.vue'),
    Chatbox: require('./Chatbox.vue'),
  },
  props: {
    id: String,
    title: String,
    description: String,
    users: Array,
    messages: Array,
  },
  computed: {
    characters() {
      return this.$store.state.chat.characters
    },
    identity() {
      return this.$store.state.chat.identity
    },
  },
  methods: {
    parseBBC,
    sendMessage(message) {
      this.$store.dispatch('sendChannelMessage', { id: this.id, message })
    },
  },
}
</script>

// src/components/ChannelView.tsx
import sortBy from 'lodash/sortBy'
import { observer } from 'mobx-react'
import * as React from 'react'
import { Channel, Character, Message } from '../store/chat-state'
import CharacterView from './CharacterView'
import MessageView from './MessageView'

function sortUserList(users: Character[]) {
  return sortBy(users, user => user.name.toLowerCase())
}

function renderMessageList(messages: Message[]) {
  return messages.map(msg => <MessageView message={msg} key={msg.id} />)
}

function renderUserList(users: Character[]) {
  return users.map(user =>
    <div key={user.name} style={{ width: '12em', margin: '0.4em 0.5em' }}>
      <CharacterView character={user} />
    </div>
  )
}

function ChannelView(props: { channel: Channel }) {
  const { messages, users, description } = props.channel
  const userList = Array.from(users.values())
  const sortedUsers = sortUserList(userList)
  return (
    <div className="flex-column" style={{ width: '100%', height: '100%' }}>
      <div
        className="scroll-v"
        style={{ padding: '0.5em', maxHeight: '5em' }}
        dangerouslySetInnerHTML={{ __html: description }}
      />
      <div className="flex-grow flex-row">
        <div className="flex-grow scroll-v bg-2">
          {renderMessageList(messages)}
        </div>
        <div className="scroll-v">
          {renderUserList(sortedUsers)}
        </div>
      </div>
    </div>
  )
}

export default observer(ChannelView)
