// src/components/chat/ChannelList.vue
<template>
  <overlay @shadeclick="$emit('close')">
    <div class="wrapper scroll-v bg-color-darken-1">
      <a href="#" v-for="{ id, title, userCount } in filteredChannels" :key="id" :class="['channel flex-row', joinedChannels[id] && 'channel--joined']" @pointerdown.prevent="toggleChannel(id)">
        <span class="channel-title flex-grow" v-html="title"></span>
        <span class="channel-user-count">{{ userCount }}</span>
      </a>
    </div>
    <div class="flex-row" style="padding: 0.5rem">
      <input class="flex-grow" style="margin-right: 0.5rem" placeholder="Search..." @input="updateSearchText($event.currentTarget.value)">
      <button @pointerdown="$emit('close')">Done</button>
    </div>
  </overlay>
</template>

<script>
import sortBy from 'lodash/sortBy'
import debounce from 'lodash/debounce'
import store from '@/store.new'

export default {
  data() {
    return {
      searchText: ''
    }
  },

  computed: {
    channels() {
      return store.chat.channelList
    },

    joinedChannels() {
      return store.chat.joinedChannels
    },

    sortedChannels() {
      return sortBy(this.channels, [
        ch => ch.type === 'public' ? 0 : 1,
        ch => ch.title.toLowerCase(),
      ])
    },

    filteredChannels() {
      const searchText = this.searchText.trim().toLowerCase()
      const channels = this.sortedChannels
      if (searchText === '') {
        return channels
      }
      return channels.filter(ch => ch.title.toLowerCase().includes(searchText))
    }
  },

  methods: {
    toggleChannel(id) {
      if (this.joinedChannels[id]) {
        store.chat.leaveChannel(id)
      } else {
        store.chat.joinChannel(id)
      }
    },

    updateSearchText: debounce(function(text) {
      this.searchText = text
    }, 500)
  }
}
</script>

<style lang="scss" scoped>
.wrapper {
  height: 30em;
  width: 24rem;
}

// .channel {}
.channel-title {
  padding: 0.4rem;
}

.channel-user-count {
  width: 3rem;
  padding: 0.4rem;
  text-align: right;
}

.channel--joined {
  background: rgba(46, 204, 113, 0.3);
}
</style>

// src/components/ChannelList.tsx
import sortBy = require('lodash/sortBy')
import debounce = require('lodash/debounce')
import { computed, observable } from 'mobx'
import { observer } from 'mobx-react'
import * as React from 'react'
import { ChannelInfo } from '../chat-store'
import { preventDefault } from '../lib/react-utils'

const channelListStyle: React.CSSProperties = {
  height: 'calc(100vh - 10em)',
  width: 'calc(100vw - 4em)',
  maxWidth: '30em',
}

@observer
export default class ChannelList extends React.Component {
  props: {
    channels: ChannelInfo[]
    joinedChannels: string[]
    onClose?: () => any
    onChannelInput: (id: string) => any
  }

  @observable searchText = ''

  updateSearchText = debounce((text: string) => {
    this.searchText = text
  }, 500)

  @computed
  get processedChannels() {
    const search = this.searchText.toLowerCase()
    const sorted = sortBy(this.props.channels, 'type', 'title')
    return sorted.filter(ch => ch.title.toLowerCase().includes(search))
  }

  render() {
    const renderChannel = (ch: ChannelInfo) => {
      const padding = { padding: '0.3em 0.6em' }
      const onClick = preventDefault(() => this.props.onChannelInput(ch.id))
      const joinedClass = this.props.joinedChannels.includes(ch.id) ? 'bg-1' : ''
      return (
        <a className={`flex-row ${joinedClass}`} href="#" key={ch.id} onClick={onClick}>
          <div
            style={padding}
            className="flex-grow"
            dangerouslySetInnerHTML={{ __html: ch.title }}
          />
          <div style={padding}>
            {ch.userCount}
          </div>
        </a>
      )
    }

    return (
      <div>
        <div className="bg-2 scroll-v" style={channelListStyle}>
          {this.processedChannels.map(renderChannel)}
        </div>
        <div className="flex-row" style={{ padding: '0.5em' }}>
          <input
            className="input flex-grow"
            style={{ marginRight: '0.5em' }}
            type="text"
            placeholder="Search..."
            onInput={e => this.updateSearchText(e.currentTarget.value)}
          />
          <button className="button" onClick={this.props.onClose}>
            Done
          </button>
        </div>
      </div>
    )
  }
}
