// vue/components/Toggle.vue
<template>
  <a href='#' :style="{ opacity: value ? 1 : 0.5 }" @keydown.space="$emit('click')">
    <i :class="'mdi mdi-' + iconClass"></i>
    <slot></slot>
  </a>
</template>

<style lang="stylus" scoped>
a
  font-size: 0.8em
  padding: 0.2em 0.4em
  user-select: none

span
  display: inline-block
  padding: 0.3em 0.5em
</style>

<script>
export default {
  props: {
    value: Boolean
  },

  computed: {
    iconClass () {
      return this.value ? 'checkbox-marked-circle' : 'checkbox-blank-circle-outline'
    }
  }
}
</script>

// src/components/Toggle.tsx
import * as React from 'react'
import css from './Toggle.styl?module'

export default class Toggle extends React.Component {
  props: {
    value: boolean
    children: React.ReactNode
  }

  render() {
    const iconClass = this.props.value
      ? 'mdi-checkbox-marked-outline'
      : 'mdi-checkbox-blank-outline'

    return (
      <a className={css.toggle} href="#">
        <i className={`mdi ${iconClass}`} /> {this.props.children}
      </a>
    )
  }
}
