// src/chat/components/ChatAction.tsx
import * as React from 'react'
import styled from 'styled-components'

import { Icon } from 'src/app/components/Icon'

const Wrapper = styled.a`
  opacity: 0.5;

  &:hover {
    opacity: 1;
  }
`

export function ChatAction(props: { icon: string }) {
  return (
    <Wrapper href="#" className="padding block no-line-height">
      <Icon name={props.icon} size={32} />
    </Wrapper>
  )
}

// src/components.old/chat/ChatAction.vue
<template>
  <a href='#' class="action-icon">
    <icon :size="32">{{ icon }}</icon>
  </a>
</template>

<script>
export default {
  props: {
    icon: String
  }
}
</script>


<style lang="scss" scoped>
.action-icon {
  margin: 0.5rem;
  display: block;
  opacity: 0.5;

  &:hover {
    opacity: 0.75;
  }
}
</style>
