// src/components/chat/ChatTab.vue
<template>
  <div :class="['chat-tab flex-row', active && 'chat-tab--active bg-color-main']">
    <a href="#" class="chat-tab-title flex-grow flex-row flex-align-center" @click.prevent="$emit('activate')">
      <slot></slot>
      <span class="chat-tab-title-icon">
        <slot name="icon"></slot>
      </span>
      <span class="chat-tab-title-text">
        <slot name="title"></slot>
      </span>
    </a>
    <a href="#" class="chat-tab-close flex-center" @click.prevent="$emit('close')">
      <icon>close</icon>
    </a>
  </div>
</template>

<script>
export default {
  props: {
    active: Boolean
  }
}
</script>


<style lang="scss" scoped>
.chat-tab {
  opacity: 0.5;
}

.chat-tab-title {
  padding: 0.5rem;
  width: 10rem;
  white-space: nowrap;
  overflow-x: hidden;
  text-overflow: ellipsis;
}

.chat-tab-close {
  padding: 0.5rem;
  opacity: 0.2;
  transition: 0.25s;

  &:hover {
    opacity: 0.5;
  }
}

.chat-tab--active {
  opacity: 1;
}

.chat-tab-title-text {
  margin-left: 0.3rem;
}

.chat-tab-title-icon {
  img,
  i {
    display: block;
  }
}
</style>

// src/chat/components/ChatTab.tsx
import * as React from 'react'
import styled from 'styled-components'

import { Icon } from 'src/app/components/Icon'

type ChannelTabProps = {
  children: React.ReactNode
  active?: boolean
}

const Wrapper = styled.div`
  &:hover {
    opacity: ${(props: ChannelTabProps) => (props.active ? 1 : 0.75)};
  }

  opacity: ${(props: ChannelTabProps) => (props.active ? 1 : 0.5)};
`

const CloseIcon = styled.a`
  opacity: 0.3;

  &:hover {
    opacity: 0.7;
  }
`

export function ChatTab(props: ChannelTabProps) {
  const activeClass = props.active ? 'bg-color-main' : ''
  return (
    <Wrapper className={`${activeClass} flex-row flex-align-stretch`} active={props.active}>
      <a href="#" className="flex-grow padding">
        {props.children}
      </a>
      <CloseIcon href="#" className="flex-center padding no-line-height">
        <Icon name="close" />
      </CloseIcon>
    </Wrapper>
  )
}
